if object_id('fn_Drew_Restore_People_DiffTable_t') is not null
	drop function fn_Drew_Restore_People_DiffTable_t
go

create function fn_Drew_Restore_People_DiffTable_t()
returns @DeleteCheck table(id int identity primary key, TableName varchar(255), WhereClause nvarchar(max))
as begin
	insert into @DeleteCheck(TableName, WhereClause)
	values('People', N'WHERE PeopleID = @MainRecordID'),
	('Resumes', N'WHERE PeopleID = @MainRecordID'),
	('Notes', N'WHERE PeopleID = @MainRecordID'),
	('LinkPeopleToSkills', N'WHERE PeopleID = @MainRecordID'),
	('Affiliates', N'WHERE PeopleID = @MainRecordID'),
	('Education', N'WHERE PeopleID = @MainRecordID'),
	('PeopleAvailability', N'WHERE PeopleID = @MainRecordID'),
	('LinkPeopleToCredentials', N'WHERE PeopleID = @MainRecordID'),
	('LinkPeopleToCompanies', N'WHERE PeopleID = @MainRecordID'),
	('JobOrderClientTeams', N'WHERE PeopleID = @MainRecordID'),
	('LinkPeopleToKnownToUsers', N'WHERE PeopleID = @MainRecordID'),
	('ProjectsCallStatus', N'WHERE PeopleID = @MainRecordID'),
	('Positions', N'WHERE PeopleID = @MainRecordID and isnull(ProjectsID, 0) = 0 and isnull(JobOrdersID, 0) = 0'),
	('EMailAddress', N'WHERE PeopleID = @MainRecordID'),
	('ProjectsClientTeams', N'WHERE PeopleID = @MainRecordID'),
	('EMailArchive', N'WHERE PeopleID = @MainRecordID and CompaniesID is null'),
	('InternalInterviews', N'WHERE PeopleID = @MainRecordID and Done = 0 and ProjectsID > 0'),
	('CandidateCredentials', N'WHERE CandidatePeopleID = @MainRecordID'),
	('CandidateReferrals', N'WHERE @MainRecordID in(PeopleID, SourcePeopleID)'),
	('CandidateReferences', N'WHERE @MainRecordID in(PeopleID, RefereePeopleID)'),
	('LinkCandidatesToMPContacts', N'WHERE @MainRecordID in(CandPeopleID, ContactPeopleID)'),
	('PeopleAdditionalNames', N'WHERE PeopleID = @MainRecordID'),
	('LinkPeopleToNetWork', N'WHERE @MainRecordID in(LeftID, RightID)'),
	('JobOrderConsideredPeople', N'WHERE PeopleID = @MainRecordID'),
	('JobOrderInterviewPeople', N'WHERE PeopleID = @MainRecordID'),
	('JobOrderInternalInterviewPeople', N'WHERE PeopleID = @MainRecordID'),
	('JobOrderPresentedPeople', N'WHERE PeopleID = @MainRecordID'),
	('JobOrdersSources', N'WHERE PeopleID = @MainRecordID'),
	('JobOrdersTargetCompaniesCandidates', N'WHERE PeopleID = @MainRecordID'),
	('ProjectsBenchmarkCandidates', N'WHERE PeopleID = @MainRecordID'),
	('ProjectsInternalInterviewLists', N'WHERE PeopleID = @MainRecordID'),
	('ProjectsPresentedLists', N'WHERE PeopleID = @MainRecordID'),
	('ProjectsSources', N'WHERE PeopleID = @MainRecordID'),
	('ProjectsClientEmployeesLists', N'WHERE PeopleID = @MainRecordID'),
	('ProjectsShortLists', N'WHERE PeopleID = @MainRecordID'),
	('ProjectsTargetLists', N'WHERE PeopleID = @MainRecordID'),
	('ProjectsFileSearchCandidates', N'WHERE PeopleID = @MainRecordID'),
	('LastProjectActivity', N'WHERE PeopleID = @MainRecordID'),
	('ProjectTargetCompaniesCandidates', N'WHERE PeopleID = @MainRecordID'),
	('PeopleAppliedTo', N'WHERE PeopleID = @MainRecordID'),
	('LinkContactsToTask', N'WHERE PeopleID = @MainRecordID'),
	('LinkPeopleToPackage', N'WHERE PeopleID = @MainRecordID'),
	('LinkPeopleToRates', N'WHERE PeopleID = @MainRecordID'),
	('ProjectsCandidateBlocks', N'WHERE PeopleID = @MainRecordID'),
	('EventSessionsInvitees', N'WHERE PeopleID = @MainRecordID'),
	('EventSessionVendors', N'WHERE PeopleID = @MainRecordID'),
	('LinkCandidatesToMProjects', N'WHERE PeopleID = @MainRecordID'),
	('LinkContactsToMProjects', N'WHERE PeopleID = @MainRecordID'),
	('LinkContactsToOpportunities', N'WHERE PeopleID = @MainRecordID'),
	('MProjectCompaniesContacts', N'WHERE PeopleID = @MainRecordID'),
	('Addresses', N'WHERE AddressesID in((select HomeAddressesID from <DB>..People x where x.PeopleID = @MainRecordID), (select BusinessAddressesID from <DB>..People x where x.PeopleID = @MainRecordID), (select AlternativeAddressesID from <DB>..People x where x.PeopleID = @MainRecordID))'),
	('ListsDetails', N'WHERE ListID IN(SELECT ListsID FROM <DB>..Lists WHERE SourceTable IN(''People'')) AND RecordID = @MainRecordID'),
	('LinkObjectToDocument', N'WHERE ObjectTableName = ''People'' AND LeftID = @MainRecordID'),
	('LinkObjectToTask', N'WHERE ObjectTableName = ''People'' AND LeftID = @MainRecordID'),
	('LinkObjectToActivityHistory', N'WHERE ObjectTableName = ''People'' AND LeftID = @MainRecordID'),
	('Assignments', N'WHERE PeopleID = @MainRecordID'),
	('Assignments', N'WHERE ContactPeopleID = @MainRecordID'),
	('JobOrders', N'WHERE PlacedByPeopleID = @MainRecordID'),
	('JobOrders', N'WHERE InvoiceToPeopleID = @MainRecordID'),
	('JobOrders', N'WHERE LeadContactPeopleID = @MainRecordID'),
	('JobOrders', N'WHERE ReportsToPeopleID = @MainRecordID'),
	('Projects', N'WHERE BillingToPeopleID = @MainRecordID'),
	('PositionDetails', N'WHERE PositionsID in(select PositionsID from <DB>..Positions where PeopleID = @MainRecordID and isnull(ProjectsID, 0) = 0 and isnull(JobOrdersID, 0) = 0)'),
	('LinkPositionsToRates', N'WHERE PositionsID in(select PositionsID from <DB>..Positions where PeopleID = @MainRecordID and isnull(ProjectsID, 0) = 0 and isnull(JobOrdersID, 0) = 0)'),
	('LinkJobOrderScheduleToPosition', N'WHERE PositionsID in(select PositionsID from <DB>..Positions where PeopleID = @MainRecordID and isnull(ProjectsID, 0) = 0 and isnull(JobOrdersID, 0) = 00)'),
	('LinkJobOrderToWorksteps', N'WHERE PositionsID in(select PositionsID from <DB>..Positions where PeopleID = @MainRecordID and isnull(ProjectsID, 0) = 0 and isnull(JobOrdersID, 0) = 0)'),
	('Timesheets', N'WHERE PositionsID in(select PositionsID from <DB>..Positions where PeopleID = @MainRecordID and isnull(ProjectsID, 0) = 0 and isnull(JobOrdersID, 0) = 0)'),
	('PositionExpenses', N'WHERE PositionsID in(select PositionsID from <DB>..Positions where PeopleID = @MainRecordID and isnull(ProjectsID, 0) = 0 and isnull(JobOrdersID, 0) = 0)'),
	('JobOrderPositionTeams', N'WHERE PositionsID in(select PositionsID from <DB>..Positions where PeopleID = @MainRecordID and isnull(ProjectsID, 0) = 0 and isnull(JobOrdersID, 0) = 0)'),
	('Task', N'WHERE PositionsID in(select PositionsID from <DB>..Positions where PeopleID = @MainRecordID and isnull(ProjectsID, 0) = 0 and isnull(JobOrdersID, 0) = 0)'),
	('LinkAddressToDistList', N'WHERE EMailAddressID in(select EMailAddressID from <DB>..EMailAddress where PeopleID = @MainRecordID) or DistListID in(select EMailAddressID from <DB>..EMailAddress where PeopleID = @MainRecordID)'),
	('LinkInterviewersToClientInterview', N'WHERE LeftID = @MainRecordID'),
	('EmailMsgRecipients', N'WHERE EMailArchiveID in(select EMailArchiveID from <DB>..EMailArchive where PeopleID = @MainRecordID and CompaniesID is null)'),
	('EmailMsgAttachments', N'WHERE EMailArchiveID in(select EMailArchiveID from <DB>..EMailArchive where PeopleID = @MainRecordID and CompaniesID is null)'),
	('LinkObjectToActivityHistory', N'WHERE LeftID in(select EMailArchiveID from <DB>..EMailArchive where PeopleID = @MainRecordID and CompaniesID is null) and ObjectTableName = ''EmailArchive'''),
	('Task', N'WHERE TaskID in(select TaskID from <DB>..InternalInterviews where PeopleID = @MainRecordID and Done = 0 and ProjectsID > 0)'),
	('LinkInternalInterviewsToResults', N'WHERE InternalInterviewsID in(select InternalInterviewsID from <DB>..InternalInterviews where PeopleID = @MainRecordID and Done = 0 and ProjectsID > 0)'),
	('LinkSkillsToInternalInterview', N'WHERE InternalInterviewsID in(select InternalInterviewsID from <DB>..InternalInterviews where PeopleID = @MainRecordID and Done = 0 and ProjectsID > 0)'),
	('Task', N'WHERE TaskID in(select TaskID from <DB>..LinkCandidatesToMPContacts where PeopleID = @MainRecordID)')

	return
end